In [176]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Anshu_df = pd.read_csv("Anshu-csv.csv")
Anshu_df.head()

index                               title  \
0      0                    Toy Story (1995)   
1      1                      Jumanji (1995)   
2      2             Grumpier Old Men (1995)   
3      3            Waiting to Exhale (1995)   
4      4  Father of the Bride Part II (1995)   

                                        genres              tag  
0  Adventure|Animation|Children|Comedy|Fantasy            funny  
1                   Adventure|Children|Fantasy  Highly quotable  
2                               Comedy|Romance     will ferrell  
3                         Comedy|Drama|Romance     Boxing story  
4                                       Comedy              MMA

In [177]:
def movieType(row):
    return row['genres']+row['tag']

Anshu_df["movieType"] = Anshu_df.apply(movieType, axis =1)
Anshu_df.head()

index                               title  \
0      0                    Toy Story (1995)   
1      1                      Jumanji (1995)   
2      2             Grumpier Old Men (1995)   
3      3            Waiting to Exhale (1995)   
4      4  Father of the Bride Part II (1995)   

                                        genres              tag  \
0  Adventure|Animation|Children|Comedy|Fantasy            funny   
1                   Adventure|Children|Fantasy  Highly quotable   
2                               Comedy|Romance     will ferrell   
3                         Comedy|Drama|Romance     Boxing story   
4                                       Comedy              MMA   

                                          movieType  
0  Adventure|Animation|Children|Comedy|Fantasyfunny  
1         Adventure|Children|FantasyHighly quotable  
2                        Comedy|Romancewill ferrell  
3                  Comedy|Drama|RomanceBoxing story  
4                                         ComedyMMA

In [178]:
vector = CountVectorizer()

countMatrix = vector.fit(Anshu_df["movieType"])
countMatrix = vector.transform(Anshu_df["movieType"])

print("Count Matrix:")
print()
print(countMatrix.toarray())

Count Matrix:

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [179]:
dotProduct = cosine_similarity(countMatrix)
print(dotProduct)

[[1.         0.4472136  0.25819889 ... 0.         0.         0.31622777]
 [0.4472136  1.         0.         ... 0.         0.         0.35355339]
 [0.25819889 0.         1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.31622777 0.35355339 0.         ... 0.         0.         1.        ]]


In [170]:
input_Movie = "Toy Story (1995)"

def index(title):
    return Anshu_df[Anshu_df.title == title]["index"].values[0]

movie_index = index(input_Movie)
print(movie_index)

0


In [180]:
similar = list(enumerate(dotProduct[movie_index]))
print(similar)

[(0, 0.9999999999999999), (1, 0.4472135954999579), (2, 0.25819888974716115), (3, 0.22360679774997896), (4, 0.0), (5, 0.0), (6, 0.3162277660168379), (7, 0.25819888974716115), (8, 0.0), (9, 0.19999999999999998), (10, 0.22360679774997896), (11, 0.3162277660168379), (12, 0.5163977794943223), (13, 0.0), (14, 0.25819888974716115), (15, 0.0), (16, 0.0), (17, 0.0), (18, 0.0), (19, 0.15811388300841894), (20, 0.22360679774997896), (21, 0.0), (22, 0.0), (23, 0.0), (24, 0.0), (25, 0.0), (26, 0.5163977794943223), (27, 0.0), (28, 0.18257418583505539), (29, 0.0), (30, 0.0), (31, 0.0), (32, 0.25819888974716115), (33, 0.0), (34, 0.22360679774997896), (35, 0.25819888974716115), (36, 0.0), (37, 0.0), (38, 0.0), (39, 0.0), (40, 0.25819888974716115), (41, 0.22360679774997896), (42, 0.0), (43, 0.0), (44, 0.36514837167011077), (45, 0.25819888974716115), (46, 0.0), (47, 0.22360679774997896), (48, 0.5163977794943223), (49, 0.3162277660168379), (50, 0.0), (51, 0.0), (52, 0.22360679774997896), (53, 0.51639777949

In [172]:
RecomList = sorted(similar, key=lambda x:x[1], reverse=True)

In [175]:
def title(index):
    return Anshu_df[Anshu_df.index == index]["title"].values[0]

i=0
for movie in RecomList:
    print(title(movie[0]))
    i=i+1
    if i>20:
        break

Toy Story (1995)
Aladdin (1992)
Antz (1998)
Robin Hood (1973)
Toy Story 2 (1999)
Hercules (1997)
Adventures of Rocky and Bullwinkle, The (2000)
Oliver & Company (1988)
Grand Day Out with Wallace and Gromit, A (1989)
Mulan (1998)
Goofy Movie, A (1995)
Borrowers, The (1997)
Black Cauldron, The (1985)
Jungle Book, The (1967)
Song of the South (1946)
Steamboat Willie (1928)
Secret of NIMH, The (1982)
American Tail, An (1986)
Adventures of Milo and Otis, The (Koneko monogatari) (1986)
We're Back! A Dinosaur's Story (1993)
For the Love of Benji (1977)
